### ISSUE TITLE
HTTP POST service with PHP (web database)

### ISSUE THREAD

**Issue by Happypig375** [Happypig375/InnoTech-eLearning#1]
First issue lol

**Comment by jordanfungtc** [comment]
**UPDATED**
A test webpage developed with PHP to receive POST requests and give a response separated with commas.
Host: `cloud.pedosa.org`
URI: `/solutions/cswcss-innotech/test/index.php`

Parameters to send:
1. `$STUDENT_ID` (use `s18999`)
2. `$STUDENT_PASSPHRASE` (use `Y1234567`)

Example Request Body:
`STUDENT_ID=s18999&STUDENT_PASSPHRASE=Y1234567`

Response:
`s18999,Chan Tai Man,7A,37`

Parameter 1: `$STUDENT_ID`
Parameter 2: `$STUDENT_NAME`
Parameter 3: `$STUDENT_CLASS`
Parameter 4: `$STUDENT_NO`

Comment below if you have seen this or have any questions. 

Cheers, 
Jordan

**Comment by Happypig375** [comment]
This issue was moved to CSWCSS-InnoTech/InnoTech-eLearning#1
